language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "nightly" # currently 3.7-dev
  - "pypy"

env:
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="Django>=1.8,<1.9"

matrix:
  fast_finish: true
  include:
  - python: "2.7"
    env: DJANGO_VERSION=Django~=1.7.11 djangorestframework~=2.4.8

install: 
  - pip install -q $DJANGO_VERSION
  - pip install --editable .[dev]
  - pip install --upgrade pytest

script: 
  - pip freeze
  - pytest --cov=drf_queryfields

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
