language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly" # currently 3.7-dev

install: pip install --upgrade --editable .[dev]

script: PYTHONPATH=`pwd` pytest
